log_dir = "data/logs"
progress_bar = true

[env]
dt = 0.05
max_duration = 30
min_start_buffer = 1
max_init_attempts = 10000

[scenario]
name = "random"
homogeneous = false
human_model = "orca"
policy = ["orca", "sfm", "social_momentum", "ga3c_cadrl", "sa_cadrl", "lpsnav"]

[scenario.predefined]
configuration = ["swap", "pass"]
lat_dist = 0.7
long_dist = 5
comparison_param = "configuration"
iters = 1
uniform_bnd = 0

[scenario.random]
number_of_agents = [5, 7, 9]
iters = 3
width = 8
height = 8
min_start_goal_sep = 1
des_speed_mean = 1.42
des_speed_std_dev = 0.26
comparison_param = "number_of_agents"

[scenario.circle]
number_of_agents = 8
radius = 3
comparison_param = "number_of_agents"

[scenario.custom]
starts = [[-3, 0], [3, 3]]
goals = [[3, 0], [0, -3]]

[animation]
show_ani = true
save_ani = false
ani_dir = "data/videos"
show_plot = false
save_plot = false
plot_dir = "data/plots"
dark_background = false
overlay = false
plot_goals = true
plot_body = true
body_interval = 0.4
plot_traj = true
speed = 1
autoplay = false
dpi = 96
width = 1920
height = 1080
follow_ego = false

[eval]
show_tbl = true
save_tbl = false
tbl_dir = "data/tables"
metrics = ["extra_dist", "failure"]
only_valid = true
show_barplot = false
save_barplot = false
barplot_dir = "data/barplots"
show_violinplot = false
save_violinplot = false
violinplot_dir = "data/violinplots"
tracked_metrics = ["min_mpd"]
show_tracked_metrics = false
save_tracked_metrics = false
tracked_metrics_dir = "data/tracked_metrics"
save_df = false
df_dir = "data/dataframes"

[agent]
radius = 0.25
min_speed = 0
max_speed = 1
max_accel = 3
max_ang_accel = 5
goal_tol = 0.1
heading_span = 1.57
speed_samples = 5
heading_samples = 31
prim_horiz = 1
kinematics = "second_order_unicycle"
sensing_dist = 20
col_horiz = 1

[agent.inattentive]
name = "Inattentive"
color = "#8c8787"

[agent.lpsnav]
name = "LPSNav"
color = "#785ef0"
legibility_tol = -0.02
predictability_tol = 0.05
subgoal_priors = [0.48, 0.02, 0.5]
longitudinal_space = [0.1, 0.5]
lateral_space = [0.1, 0.2]
receding_horiz = 5
sensing_horiz = 10
max_cost = 1e2

[agent.orca]
name = "ORCA"
color = "#a9a5a5"
max_neighbors = 10
time_horiz = 5
neighbor_dist = 10
scaled_radius = 1.1

[agent.sfm]
name = "SFM"
color = "#c3c0c0"
tau = 0.5
sigma = 0.3
v_ab0 = 2.1
phi = 1.7453
c = 0.5
step_width = 2
u_ab0 = 10
R = 0.2

[agent.social_momentum]
name = "SM"
color = "#7293dc"
weight = 0.005

[agent.sa_cadrl]
name = "SA-CADRL"
color = "#dcc572"
getting_close_penalty = -0.05
eps = 1e-5
getting_close_range = 0.2
collision_cost = -0.25
gamma = 0.97
dt_normal = 0.5
dist_2_goal_thres = 0.05

[agent.ga3c_cadrl]
name = "GA3C-CADRL"
color = "#dca272"
