[environment]
timestep = 0.1
max_duration = 10
eval = true
# passing, 2_agent_split, circle, random, swap, t_junction, 2_agent_t_junction, custom
scenario = "custom"
random_scenarios = 10
homogeneous = false
human_policy = "rvo"
# policies = ["legitable", "rvo", "social_momentum", "sa_cadrl", "ga3c_cadrl"]
policies = ["legitable"]
num_of_agents = 5
# [[[agent_1_start], [agent_1_goal]], [[agent_2_start], [agent_2_goal]], ...]
# custom_pos = [[[3.39, 1.68], [1.24, 3.01]], [[3.56, 3.35], [2.18, 1.82]]]
# custom_pos = [[[0, 0], [8, 0]], [[0.4, 2], [8, -2]]]
# custom_pos = [[[3.39, 1.68], [1.24, 3.01]], [[3.56, 3.35], [2.18, 1.82]]]
# custom_pos = [[[3.21, 0.54], [2.41, 4.21]], [[0.40, 4.01], [0.46, 1.66]], [[4.75, 2.78], [5.43, 5.70]]]
# custom_pos = [[[-4, 0], [4, 0]], [[0, 0], [0, 0]]]
# custom_pos = [[[0.39, 1.91], [3.42, 5.61]], [[2.61, 5.48], [5.90, 5.98]], [[3.52, 3.14], [3.46, 1.12]]]
# custom_pos = [[[3.87, 6.94], [6.50, 8.61]], [[9.41, 8.03], [2.42, 8.73]], [[5.22, 9.45], [3.46, 4.63]]]
# custom_pos = [[[1.35, 8.87], [4.87, 0.46]], [[4.77, 9.89], [5.14, 7.47]], [[5.36, 0.52], [5.76, 9.45]], [[8.13, 2.19], [5.06, 3.43]], [[2.01, 5.22], [2.90, 1.51]]]
# custom_pos = [[[1.80, 4.47], [5.05, 8.67]], [[1.99, 8.63], [5.18, 2.09]], [[4.22, 2.36], [8.23, 9.98]], [[5.34, 0.44], [8.58, 3.22]], [[6.50, 4.18], [0.45, 0.32]]]
# custom_pos = [[[6.79, 8.12], [4.70, 7.93]], [[2.04, 3.89], [7.21, 4.29]], [[9.56, 5.82], [5.88, 5.91]], [[1.53, 9.91], [0.13, 4.35]], [[4.48, 4.92], [2.45, 3.66]]]
custom_pos = [[[5.47, 7.80], [7.61, 0.80]], [[7.66, 3.04], [1.74, 1.45]], [[3.14, 2.72], [5.88, 1.81]], [[0.51, 6.87], [6.62, 7.37]], [[5.50, 3.91], [9.04, 7.32]]]
# custom_pos = [[[5.47, 7.80], [7.61, 0.80]], [[0.51, 6.87], [6.62, 7.37]], [[5.50, 3.91], [9.04, 7.32]]]
circle_radius = 5
workspace_length = 10
interaction_dist = 8
lat_dist = 0.8
precision = 13
min_start_buffer = 1.5

[animation]
show_ani = true
save_ani = false
ani_dir = "data/videos"
show_plot = false
save_plot = false
plot_dir = "data/plots"
dark_bkg = true
overlay = true
plot_body = true
body_interval = 0.3
plot_traj = true
debug = false

[agent]
radius = 0.25
min_speed = 0
max_speed = 1
max_accel = 1
max_ang_accel = 3
goal_tol = 0.1
heading_span = 1.047
speed_samples = 9
heading_samples = 15
# speed_samples = 4
# heading_samples = 5
prim_horiz = 1.5
kinematics = "second_order_unicycle"

[policy]
sensing_dist = 5

[legitable]
legibility_tol = 1.15
subgoal_priors = [0.47, 0.02, 0.49]
col_buffer = 0.8
receding_horiz = 2
scaled_speed = 2

[rvo]
rvo_max_neighbors = 10
rvo_time_horiz = 5
rvo_neighbor_dist = 10

[social-momentum]
sm_weight = 0.96
